// Generated by gencpp from file robotino_node/ResetOdometry.msg
// DO NOT EDIT!


#ifndef ROBOTINO_NODE_MESSAGE_RESETODOMETRY_H
#define ROBOTINO_NODE_MESSAGE_RESETODOMETRY_H

#include <ros/service_traits.h>


#include <robotino_node/ResetOdometryRequest.h>
#include <robotino_node/ResetOdometryResponse.h>


namespace robotino_node
{

struct ResetOdometry
{

typedef ResetOdometryRequest Request;
typedef ResetOdometryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetOdometry
} // namespace robotino_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotino_node::ResetOdometry > {
  static const char* value()
  {
    return "400210218ff66e5bce9e5be16653c0c8";
  }

  static const char* value(const ::robotino_node::ResetOdometry&) { return value(); }
};

template<>
struct DataType< ::robotino_node::ResetOdometry > {
  static const char* value()
  {
    return "robotino_node/ResetOdometry";
  }

  static const char* value(const ::robotino_node::ResetOdometry&) { return value(); }
};


// service_traits::MD5Sum< ::robotino_node::ResetOdometryRequest> should match 
// service_traits::MD5Sum< ::robotino_node::ResetOdometry > 
template<>
struct MD5Sum< ::robotino_node::ResetOdometryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_node::ResetOdometry >::value();
  }
  static const char* value(const ::robotino_node::ResetOdometryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_node::ResetOdometryRequest> should match 
// service_traits::DataType< ::robotino_node::ResetOdometry > 
template<>
struct DataType< ::robotino_node::ResetOdometryRequest>
{
  static const char* value()
  {
    return DataType< ::robotino_node::ResetOdometry >::value();
  }
  static const char* value(const ::robotino_node::ResetOdometryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotino_node::ResetOdometryResponse> should match 
// service_traits::MD5Sum< ::robotino_node::ResetOdometry > 
template<>
struct MD5Sum< ::robotino_node::ResetOdometryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_node::ResetOdometry >::value();
  }
  static const char* value(const ::robotino_node::ResetOdometryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_node::ResetOdometryResponse> should match 
// service_traits::DataType< ::robotino_node::ResetOdometry > 
template<>
struct DataType< ::robotino_node::ResetOdometryResponse>
{
  static const char* value()
  {
    return DataType< ::robotino_node::ResetOdometry >::value();
  }
  static const char* value(const ::robotino_node::ResetOdometryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTINO_NODE_MESSAGE_RESETODOMETRY_H
