// Generated by gencpp from file robotino_node/SetEncoderPosition.msg
// DO NOT EDIT!


#ifndef ROBOTINO_NODE_MESSAGE_SETENCODERPOSITION_H
#define ROBOTINO_NODE_MESSAGE_SETENCODERPOSITION_H

#include <ros/service_traits.h>


#include <robotino_node/SetEncoderPositionRequest.h>
#include <robotino_node/SetEncoderPositionResponse.h>


namespace robotino_node
{

struct SetEncoderPosition
{

typedef SetEncoderPositionRequest Request;
typedef SetEncoderPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEncoderPosition
} // namespace robotino_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotino_node::SetEncoderPosition > {
  static const char* value()
  {
    return "e17f4b08b3e2cdbbf2b0d78e4f62e5d6";
  }

  static const char* value(const ::robotino_node::SetEncoderPosition&) { return value(); }
};

template<>
struct DataType< ::robotino_node::SetEncoderPosition > {
  static const char* value()
  {
    return "robotino_node/SetEncoderPosition";
  }

  static const char* value(const ::robotino_node::SetEncoderPosition&) { return value(); }
};


// service_traits::MD5Sum< ::robotino_node::SetEncoderPositionRequest> should match 
// service_traits::MD5Sum< ::robotino_node::SetEncoderPosition > 
template<>
struct MD5Sum< ::robotino_node::SetEncoderPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_node::SetEncoderPosition >::value();
  }
  static const char* value(const ::robotino_node::SetEncoderPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_node::SetEncoderPositionRequest> should match 
// service_traits::DataType< ::robotino_node::SetEncoderPosition > 
template<>
struct DataType< ::robotino_node::SetEncoderPositionRequest>
{
  static const char* value()
  {
    return DataType< ::robotino_node::SetEncoderPosition >::value();
  }
  static const char* value(const ::robotino_node::SetEncoderPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotino_node::SetEncoderPositionResponse> should match 
// service_traits::MD5Sum< ::robotino_node::SetEncoderPosition > 
template<>
struct MD5Sum< ::robotino_node::SetEncoderPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_node::SetEncoderPosition >::value();
  }
  static const char* value(const ::robotino_node::SetEncoderPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_node::SetEncoderPositionResponse> should match 
// service_traits::DataType< ::robotino_node::SetEncoderPosition > 
template<>
struct DataType< ::robotino_node::SetEncoderPositionResponse>
{
  static const char* value()
  {
    return DataType< ::robotino_node::SetEncoderPosition >::value();
  }
  static const char* value(const ::robotino_node::SetEncoderPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTINO_NODE_MESSAGE_SETENCODERPOSITION_H
