(cl:defpackage robotino_msgs-msg
  (:use )
  (:export
   "<ANALOGREADINGS>"
   "ANALOGREADINGS"
   "<BHAREADINGS>"
   "BHAREADINGS"
   "<DIGITALREADINGS>"
   "DIGITALREADINGS"
   "<ENCODERREADINGS>"
   "ENCODERREADINGS"
   "<GRAPPLERREADINGS>"
   "GRAPPLERREADINGS"
   "<GRIPPERSTATE>"
   "GRIPPERSTATE"
   "<MOTORREADINGS>"
   "MOTORREADINGS"
   "<NORTHSTARREADINGS>"
   "NORTHSTARREADINGS"
   "<POWERREADINGS>"
   "POWERREADINGS"
   "<SETBHAPRESSURES>"
   "SETBHAPRESSURES"
   "<SETGRAPPLERAXES>"
   "SETGRAPPLERAXES"
   "<SETGRAPPLERAXIS>"
   "SETGRAPPLERAXIS"
  ))

