// Generated by gencpp from file robotino_local_move/LocalMoveResult.msg
// DO NOT EDIT!


#ifndef ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVERESULT_H
#define ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotino_local_move
{
template <class ContainerAllocator>
struct LocalMoveResult_
{
  typedef LocalMoveResult_<ContainerAllocator> Type;

  LocalMoveResult_()
    : goal_reached(false)  {
    }
  LocalMoveResult_(const ContainerAllocator& _alloc)
    : goal_reached(false)  {
    }



   typedef uint8_t _goal_reached_type;
  _goal_reached_type goal_reached;




  typedef boost::shared_ptr< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct LocalMoveResult_

typedef ::robotino_local_move::LocalMoveResult_<std::allocator<void> > LocalMoveResult;

typedef boost::shared_ptr< ::robotino_local_move::LocalMoveResult > LocalMoveResultPtr;
typedef boost::shared_ptr< ::robotino_local_move::LocalMoveResult const> LocalMoveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotino_local_move::LocalMoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotino_local_move

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robotino_local_move': ['/home/simon/catkin_ws/devel/share/robotino_local_move/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a65bc774d2139031955fd7cc94fdd40f";
  }

  static const char* value(const ::robotino_local_move::LocalMoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa65bc774d2139031ULL;
  static const uint64_t static_value2 = 0x955fd7cc94fdd40fULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotino_local_move/LocalMoveResult";
  }

  static const char* value(const ::robotino_local_move::LocalMoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool goal_reached #true if goal is reached\n\
";
  }

  static const char* value(const ::robotino_local_move::LocalMoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_reached);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct LocalMoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_local_move::LocalMoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotino_local_move::LocalMoveResult_<ContainerAllocator>& v)
  {
    s << indent << "goal_reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_reached);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_LOCAL_MOVE_MESSAGE_LOCALMOVERESULT_H
