# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robotino_msgs/SetGrapplerAxis.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class SetGrapplerAxis(genpy.Message):
  _md5sum = "a709aba75be9516258888daf559c39d4"
  _type = "robotino_msgs/SetGrapplerAxis"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time stamp
uint32 axis			# axis number (axes start from 0)
float32 angle		# in degrees
float32 velocity	# in rpm"""
  __slots__ = ['stamp','axis','angle','velocity']
  _slot_types = ['time','uint32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,axis,angle,velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetGrapplerAxis, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.axis is None:
        self.axis = 0
      if self.angle is None:
        self.angle = 0.
      if self.velocity is None:
        self.velocity = 0.
    else:
      self.stamp = genpy.Time()
      self.axis = 0
      self.angle = 0.
      self.velocity = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I2f().pack(_x.stamp.secs, _x.stamp.nsecs, _x.axis, _x.angle, _x.velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.stamp.secs, _x.stamp.nsecs, _x.axis, _x.angle, _x.velocity,) = _get_struct_3I2f().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I2f().pack(_x.stamp.secs, _x.stamp.nsecs, _x.axis, _x.angle, _x.velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.stamp.secs, _x.stamp.nsecs, _x.axis, _x.angle, _x.velocity,) = _get_struct_3I2f().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I2f = None
def _get_struct_3I2f():
    global _struct_3I2f
    if _struct_3I2f is None:
        _struct_3I2f = struct.Struct("<3I2f")
    return _struct_3I2f
