// Generated by gencpp from file robotino_msgs/BHAReadings.msg
// DO NOT EDIT!


#ifndef ROBOTINO_MSGS_MESSAGE_BHAREADINGS_H
#define ROBOTINO_MSGS_MESSAGE_BHAREADINGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotino_msgs
{
template <class ContainerAllocator>
struct BHAReadings_
{
  typedef BHAReadings_<ContainerAllocator> Type;

  BHAReadings_()
    : stamp()
    , pressures()
    , cablepull()  {
    }
  BHAReadings_(const ContainerAllocator& _alloc)
    : stamp()
    , pressures(_alloc)
    , cablepull(_alloc)  {
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pressures_type;
  _pressures_type pressures;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _cablepull_type;
  _cablepull_type cablepull;




  typedef boost::shared_ptr< ::robotino_msgs::BHAReadings_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_msgs::BHAReadings_<ContainerAllocator> const> ConstPtr;

}; // struct BHAReadings_

typedef ::robotino_msgs::BHAReadings_<std::allocator<void> > BHAReadings;

typedef boost::shared_ptr< ::robotino_msgs::BHAReadings > BHAReadingsPtr;
typedef boost::shared_ptr< ::robotino_msgs::BHAReadings const> BHAReadingsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotino_msgs::BHAReadings_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotino_msgs::BHAReadings_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotino_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robotino_msgs': ['/home/simon/catkin_ws/src/robotino-ros-pkg/robotino_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::BHAReadings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotino_msgs::BHAReadings_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::BHAReadings_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotino_msgs::BHAReadings_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::BHAReadings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotino_msgs::BHAReadings_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotino_msgs::BHAReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db28e0e5f4b0a0da881baf9c7f3c94a1";
  }

  static const char* value(const ::robotino_msgs::BHAReadings_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb28e0e5f4b0a0daULL;
  static const uint64_t static_value2 = 0x881baf9c7f3c94a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_msgs::BHAReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotino_msgs/BHAReadings";
  }

  static const char* value(const ::robotino_msgs::BHAReadings_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotino_msgs::BHAReadings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n\
float32[] pressures	# in bar\n\
float32[] cablepull\n\
";
  }

  static const char* value(const ::robotino_msgs::BHAReadings_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotino_msgs::BHAReadings_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.pressures);
      stream.next(m.cablepull);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BHAReadings_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_msgs::BHAReadings_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotino_msgs::BHAReadings_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "pressures[]" << std::endl;
    for (size_t i = 0; i < v.pressures.size(); ++i)
    {
      s << indent << "  pressures[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pressures[i]);
    }
    s << indent << "cablepull[]" << std::endl;
    for (size_t i = 0; i < v.cablepull.size(); ++i)
    {
      s << indent << "  cablepull[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.cablepull[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_BHAREADINGS_H
